[package]
name = "qft"
version = "0.5.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0"
time = "0"
lz4_flex = { version = "0.11", default-features = false }
